### ISSUE TITLE
scaling to new goals

### ISSUE THREAD

**Issue by jacknlliu** [stulp/dmpbbo#22]
In the [document](http://freekstulp.net/dmpbbo/html/page_dmp.html), I find this repo still not provide the function for scaling towards new goals.
![$$\begin{bmatrix} \dot{z} \\ \dot{y} \end{bmatrix} = \begin{bmatrix} (\alpha_y(\beta_y (y^{g_d} - y) -z) + v \cdot f(x))/\tau \\ z / \tau  \end{bmatrix}  $$](http://latex.codecogs.com/gif.latex?%5Cbegin%7Bbmatrix%7D%20%5Cdot%7Bz%7D%20%5C%5C%20%5Cdot%7By%7D%20%5Cend%7Bbmatrix%7D%20%3D%20%5Cbegin%7Bbmatrix%7D%20%28%5Calpha_y%28%5Cbeta_y%20%28y%5E%7Bg_d%7D%20-%20y%29%20-z%29%20&plus;%20v%20%5Ccdot%20f%28x%29%29/%5Ctau%20%5C%5C%20z%20/%20%5Ctau%20%5Cend%7Bbmatrix%7D)

Is it possible to use the traditional method for scaling towards novel goals like the following equation?

![$$\begin{bmatrix} \dot{z} \\ \dot{y} \end{bmatrix} = \begin{bmatrix} (\alpha_y(\beta_y (y^{g_d} - y) -z) + v \cdot f(x) \cdot (g-y_0)))/\tau \\ z / \tau  \end{bmatrix}  $$](http://latex.codecogs.com/gif.latex?%5Cbegin%7Bbmatrix%7D%20%5Cdot%7Bz%7D%20%5C%5C%20%5Cdot%7By%7D%20%5Cend%7Bbmatrix%7D%20%3D%20%5Cbegin%7Bbmatrix%7D%20%28%5Calpha_y%28%5Cbeta_y%20%28y%5E%7Bg_d%7D%20-%20y%29%20-z%29%20&plus;%20v%20%5Ccdot%20f%28x%29%20%5Ccdot%20%28g-y_0%29%29%29/%5Ctau%20%5C%5C%20z%20/%20%5Ctau%20%5Cend%7Bbmatrix%7D)

**Comment by jacknlliu** [comment]
It seems that only python codes lack the scaling part.

**Comment by stulp** [comment]
Yes, the python implementation contains a subset of features of the C++ implementation. Basically, I leave it that way until someone asks for a feature to be ported, as you have now done ;-)

Implementing it should be straightforward (the functionality is already there in the Dmp.py file, but commented out because it is still in C++), but I will not have time during the next few days. If you need the feature sooner, why not have a shot at it yourself, and I can merge your fork into the main repo. Your contribution would be appreciated!

**Comment by jacknlliu** [comment]
OK, I will make a PR for this.

**Comment by stulp** [comment]
See demo of this new feature in demos_python/dmp/demoDmpChangeGoal.py
