### ISSUE TITLE
dmp_bb_robot readme

### ISSUE THREAD

**Issue by studywolf** [stulp/dmpbbo#44]
It would be helpful if there could be a one liner be added about the use of the `demo_one_update` and `demo_perform_rollouts` be added in the readme on what the input directory is expected to contain. I didn't see anything in the referenced section of the docs about use of those files specifically.

**Comment by stulp** [comment]
Thanks for pointing this out. I am working on a complete revision of the documentation in the branch "revise_documentation". The main change will be to move the tutorial from the doxygen documentation to Markdown files. The main aim of the doxygen documentation will be to document the API.

During this major revision, I will include your suggestion above.

**Comment by stulp** [comment]
I'm done converting the tutorials to Markdown files. However, I have not yet described demos/dmp_bbo_robot/ yet. It needs an overhaul, which is a bit more work. The things to do (note to self):

* The bash script should call an executable compiled from demo_perform_rollouts.cpp, which needs to be written. This represents the "robot", and it generates a roll-outs using a DMP.
* This requires ensuring that all serialization functionality is there, which is very finicky with boost::serialization.
* The directory dmpbbo/demos/dmp_bbo_robot should move one level up, to dmpbbo/demos_robot/, because the best solution to running dmpbbo on a real robot is to mix Python (for running/visualizing the optimization) and C++ (for running DMPs  on the robot in real-time).
* Then the tutorial should be rewritten according to this new structure.

On the stack!

**Comment by stulp** [comment]
The overhaul of boost::serialization and writing a tutorial for dmp_bbo_robot is done. The demo is here: 
https://github.com/stulp/dmpbbo/tree/master/demo_robot
and the explanation is here:
https://github.com/stulp/dmpbbo/blob/master/tutorial/dmp_bbo_robot.md
