### ISSUE TITLE
train multiple trajectories with different initial and attractor

### ISSUE THREAD

**Issue by jacknlliu** [stulp/dmpbbo#52]
Could current implement of DMPs train multiple trajectories with different init and attractor?

**Comment by stulp** [comment]
Yes, this is possible with a ContextualDmp. See for instance this demo:
https://github.com/stulp/dmpbbo/blob/master/demos_cpp/dmp/demoDmpContextualGoal.cpp

The important line is this one, where a function approximator that maps the task parameters to the goal parameters is passed to the contextual DMP. 
https://github.com/stulp/dmpbbo/blob/master/demos_cpp/dmp/demoDmpContextualGoal.cpp#L137

This function "policy_parameter_function_goal" is denoted "m" in this paper:
http://www.isir.upmc.fr/files/2013ACTI2891.pdf
"Because the goal must be adapted, we also learn a mapping xg=m(q)". This is what you are interested in, and this is what is illustrated in demoDmpContextualGoal.

(It would be straightforward to code the same for the initial position.)

**Comment by jacknlliu** [comment]
@stulp thanks, it's what I expected. And it's nice if a python version is provided.
