### ISSUE TITLE
pass the via point

### ISSUE THREAD

**Issue by wangziyang123456** [stulp/dmpbbo#81]
Excuse me, in the task of passing a point, I used a custom track and changed the point to pass. After learning, the generation curve passed through the via point, but it did not reach the end point. What is the reason? I have studied it myself and did not understand it.

**Comment by stulp** [comment]
Does #79  help?

**Comment by wangziyang123456** [comment]
The problem seems different. I used the code passing a certain point in the python file. The original code can still pass through the endpoint after using noise interference. After I replace the code part in front of the original code with my own track, the code will not pass through the endpoint. I have read the code for a long time, but I can't find the reason. I don't know if you have had similar situations before
![A3NXH 8FP1PMCI}8_H9{F89](https://user-images.githubusercontent.com/53567096/197315860-d5f43191-855a-4ac4-8562-3c1780bbaba0.png)
.
Thank you.

**Comment by stulp** [comment]
Someone else was mentioning this, so I should have a closer look. Did you fork the code? Can you show me the exact commit where the problem arises? Thank you.

**Comment by wangziyang123456** [comment]
Under the directory demo/python/bbo_of_dmps/, I replaced the part of the file that defines DMP in demo_bbo_of_dmps_step_by_step.py, and used my own track to define DMP, do not change anything else. The dataset uses the letter e written by myself.
Thank you.
[dmp_bbo_py.txt](https://github.com/st
[news_data.txt](https://github.com/stulp/dmpbbo/files/9843870/news_data.txt)
ulp/dmpbbo/files/9843869/dmp_bbo_py.txt)

**Comment by stulp** [comment]
Thank you. The data alone is not sufficient to reproduce your observations. Please provide a link to the fork you have made, and the commit in which the problem arises. Only then can I reproduce what you see.

**Comment by wangziyang123456** [comment]
You can try to run the demos/python/bbo_of_dmps/dmp_bbo.py  file
[dmpbbp.zip](https://github.com/stulp/dmpbbo/files/9843974/dmpbbp.zip)

**Comment by stulp** [comment]
Sorry, I don't time to debug code in zip files. 

I ran the scripts myself and could not reproduce the bug, but made several improvements to the code in 0781bc4cfed32c which should help you and others:
* You can pass a trajectory now, e.g. `python3 demo_bbo_of_dmps_step_by_step.py news_data.txt`
* There is more debugging info, which needs switching on with `plot_dmp = True`
* `integrate_dmp_beyond_tau_factor` is currently 1.5. If you set it to for example 5 the trajectory should converge to the goal. If not, then indeed there is a problem.

Note that `demo_bbo_of_dmps_step_by_step.py` writes intermediate results to a temporary directory. So make sure to delete this temporary directory (or make a backup somewhere in case it is useful) when running the script again (otherwise the script may read old data). You can also pass it a directory with `demo_bbo_of_dmps_step_by_step.py --dir my_output_directory`.

In general, if you do not need the intermediate results stored (i.e. you're just testing things to start out), then I recommend using `demo_bbo_of_dmps.py`. It has the same functionality, but is much faster because it does not write files to disk.

Hope it helps.

**Comment by wangziyang123456** [comment]
Thank you for your reply. I've tried everything you said before. I'll try to find out what the problem is later.
Thanks again.
